# Generated by Django 4.2.5 on 2023-10-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variables",
            name="values",
        ),
        migrations.AddField(
            model_name="values",
            name="Variables",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="variables.variables",
            ),
        ),
    ]
