# Generated by Django 4.2.5 on 2023-10-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0002_remove_variables_values_values_variables"),
    ]

    operations = [
        migrations.RenameField(
            model_name="values",
            old_name="Variables",
            new_name="variables",
        ),
    ]
