# Generated by Django 4.2.5 on 2023-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("recipes", "0003_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, default="", to="tag.tag"),
        ),
    ]
