# Generated by Django 4.2.5 on 2023-10-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("recipes", "0005_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, default=None, to="tag.tag"),
        ),
    ]
