# Generated by Django 4.2.5 on 2023-10-17 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0006_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, default="", to="tag.tag"),
        ),
    ]
